runtime: nodejs20
service: tikeria-fe

handlers:

- url: /(.*\.[\w\d]+)$
  static_files: dist/\1
  upload: dist/(.*\.[\w\d]+)$
  http_headers:
    Cache-Control: 'public, max-age=31536000'


- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
