steps:
  - name: node:20
    entrypoint: bash
    args:
      - -c
      - |
        npm install
        npm run build

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - gcloud app deploy --quiet

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
